[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["Pavel Grim <3780785+pavel1269@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
